function G = grafo_por_trafico(datos)

% === Definimos conexiones manuales como antes ===
origenes = [...
    "Bilbao", "Bilbao", "Bilbao", "Bilbao", "Bilbao", ...
    "Barakaldo", "Barakaldo", "Basauri", "Basauri", ...
    "Getxo", "Portugalete", "Leioa", ...
    "Vitoria-Gasteiz", "Vitoria-Gasteiz", "Vitoria-Gasteiz", ...
    "Galdakao", "Durango", "Eibar", "Zarautz", "Tolosa", ...
    "Tolosa", "Errenteria", "Hernani", "Donostia/San Sebastián", ...
    "Irun", "Hondarribia", "Arrasate/Mondragón"];

destinos = [...
    "Barakaldo", "Basauri", "Getxo", "Erandio", "Galdakao", ...
    "Sestao", "Portugalete", "Galdakao", "Leioa", ...
    "Leioa", "Santurtzi", "Erandio", ...
    "Durango", "Arrasate/Mondragón", "Eibar", ...
    "Durango", "Eibar", "Zarautz", "Tolosa", "Donostia/San Sebastián", ...
    "Hernani", "Hernani", "Donostia/San Sebastián", "Errenteria", ...
    "Errenteria", "Irun", "Eibar"];

% === Calcular pesos por tráfico medio (Traf_Med)
n = numel(origenes);
pesos = zeros(n, 1);

for i = 1:n
    % Busca el tráfico medio de los dos extremos y usa la media
    idx1 = strcmp(datos.Ciudad, origenes(i));
    idx2 = strcmp(datos.Ciudad, destinos(i));

    if any(idx1) && any(idx2)
        traf1 = datos.Traf_Med(idx1);
        traf2 = datos.Traf_Med(idx2);
        pesos(i) = mean([traf1, traf2]);  % media de tráfico
    else
        pesos(i) = 1000;  % por si falta alguna ciudad (peso alto)
    end
end

% === Crear grafo con pesos por tráfico ===
G = graph(origenes, destinos, pesos);

end
